
# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

# Spring Configuration
spring:
  application:
    name: Multi_Channel_Notification_Management_System

  # Database Configuration (MySQL)
  datasource:
    url: jdbc:mysql://localhost:3306/notification_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
    open-in-view: false

  # Mail Configuration (Gmail SMTP)
  mail:
    host: smtp.gmail.com
    port: 587
    username: mahmoudbelayeb@gmail.com
    password:   # ?? Remplacez par VOTRE mot de passe d'application (16 caractères)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
        debug: true  # Pour voir les logs détaillés
    default-encoding: UTF-8


# Logging Configuration
logging:
  level:
    root: INFO
    com.notification.system: DEBUG
    org.springframework.web: INFO
    org.springframework.mail: DEBUG
    com.twilio: DEBUG  # Activer les logs Twilio
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/notification-system.log
    max-size: 10MB
    max-history: 30

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Application Custom Properties
notification:
  retry:
    max-attempts: 3
    delay-ms: 5000
  templates:
    cache-enabled: true
    preload: true

# Optional: Twilio Configuration (if using real SMS)
twilio:
  enabled: false
  account:
    sid:
  auth:
    token:
  phone:
    number:

# Optional: Firebase Configuration (if using real Push notifications)
firebase:
  enabled: false
  credentials:
    path: classpath:firebase-service-account.json


