spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification_db
    username: YOUR_DB_USERNAME
    password: YOUR_DB_PASSWORD

  mail:
    host: smtp.gmail.com
    port: 587
    username: YOUR_EMAIL@gmail.com
    password: YOUR_GMAIL_APP_PASSWORD

twilio:
  enabled: true
  account:
    sid: YOUR_TWILIO_ACCOUNT_SID
  auth:
    token: YOUR_TWILIO_AUTH_TOKEN
  phone:
    number: YOUR_TWILIO_PHONE_NUMBER

firebase:
  enabled: true
  credentials:
    path: classpath:firebase-credentials.json
